apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecost-turndown
  labels:
    app: kubecost-turndown
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecost-turndown
  labels:
    app: kubecost-turndown
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - deployments
      - nodes
      - pods
      - events
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
      - pods/eviction
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - patch 
      - delete
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - get 
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecost-turndown
  labels:
    app: kubecost-turndown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubecost-turndown
subjects:
  - kind: ServiceAccount
    name: kubecost-turndown
    namespace: kubecost
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubecost-turndown
  labels:
    app: kubecost-turndown
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-turndown
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: kubecost-turndown
  template:
    metadata:
      labels:
        app: kubecost-turndown
    spec:
      containers:
      - name: kubecost-turndown
        image: gcr.io/kubecost1/kubecost-turndown:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: turndown-volume
          mountPath: /var/configs
        - name: turndown-keys
          mountPath: /var/keys
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/keys/service-key.json
        ports:
        - name: http-server
          containerPort: 9731
          hostPort: 9731
      serviceAccount: kubecost-turndown
      serviceAccountName: kubecost-turndown
      volumes:
      - name: turndown-volume
        persistentVolumeClaim:
          claimName: kubecost-turndown
      - name: turndown-keys
        secret:
          secretName: kubecost-turndown-service-key
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: kubecost-turndown-service
spec:
  type: ClusterIP
  ports:
  - name: kubecost-turndown
    protocol: TCP
    port: 9731
    targetPort: 9731
  selector:
    app: kubecost-turndown
