apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-turndown
  namespace: turndown
  labels:
    app: cluster-turndown
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-turndown
  labels:
    app: cluster-turndown
rules:
  - apiGroups:
      - kubecost.k8s.io
    resources:
      - turndownschedules
      - turndownschedules/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - deployments
      - nodes
      - pods
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - pods/eviction
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - endpoints
      - events
      - services
    verbs:
      - get 
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - get 
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-turndown
  labels:
    app: cluster-turndown
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-turndown
subjects:
  - kind: ServiceAccount
    name: cluster-turndown
    namespace: turndown
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-turndown
  namespace: turndown
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: cluster-turndown
  template:
    metadata:
      namespace: turndown
      labels:
        app: cluster-turndown
    spec:
      containers:
      - name: cluster-turndown
        image: gcr.io/kubecost1/cluster-turndown:v1.0-SNAPSHOT
        volumeMounts:
        - name: turndown-keys
          mountPath: /var/keys
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TURNDOWN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/keys/service-key.json
        ports:
        - name: http-server
          containerPort: 9731
          hostPort: 9731
      serviceAccount: cluster-turndown
      serviceAccountName: cluster-turndown
      volumes:
      - name: turndown-keys
        secret:
          secretName: cluster-turndown-service-key
---
# TurndownSchedule Custom Resource Definition for persistence
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: turndownschedules.kubecost.k8s.io
spec:
  group: kubecost.k8s.io
  version: v1alpha1
  names:
    kind: TurndownSchedule
    singular: turndownschedule
    plural: turndownschedules
    shortNames:
    - td
    - tds
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            start: 
              type: string
              format: date-time
            end:
              type: string
              format: date-time
            repeat: 
              type: string
              enum: [none, daily, weekly]