apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: turndownschedules.kubecost.k8s.io
spec:
  group: kubecost.k8s.io
  version: v1alpha1
  names:
    kind: TurndownSchedule
    singular: turndownschedule
    plural: turndownschedules
    shortNames:
    - td
    - tds
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            start: 
              type: string
              format: date-time
            end:
              type: string
              format: date-time
            repeat: 
              type: string
              enum: [none, daily, weekly]


